apiVersion: v1
kind: Service
metadata:
  name: pdd-dashboard-service
# --- EKS deployment: uncomment block below and comment the "spec" block (Local) when deploying to EKS ---
# spec:
#   type: LoadBalancer
#   selector:
#     app: pdd-dashboard
#   ports:
#     - port: 80
#       targetPort: 8050
spec:
  type: NodePort
  selector:
    app: pdd-dashboard
  ports:
    - port: 80
      targetPort: 8050
      nodePort: 30080